### ISSUE TITLE
Attributions is buggy with 0.4

### ISSUE THREAD

**Issue by sa3m** [azgs/azgs-leaflet#1]
Hi there,

First, thanks for this plugin.
I'm working with Leaflet 0.4 and I found an issue with dynamic attributions when using other layers.
The problem is when you change layer to Bing, sometimes it won't show Bing's attribution but it will appear only when you change to another layer.
I think it comes from the dynamic attribution that answer after attribution control does its effect, so the attribution known by the control is null and the attribution is updated by the Bing layer after that.
Sorry for my technical english, it's not so good.

**Comment by rclark** [comment]
Take a look at https://github.com/shramov/leaflet-plugins/blob/master/layer/tile/Bing.js.

Pavel has done a great job of encapsulating a Bing Tile Layer.
