### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by denny123** [azgs/azgs-leaflet#4]
```
                    <script type="text/javascript" src="/leaflet-0.5.1/js/lib/less-1.2.2.min.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/lib/jade.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/lib/proj4js-1.0.3/lib/proj4js-compressed.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/azgs-leaflet/TileLayer.Bing.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/azgs-leaflet/TileLayer.ESRI.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/azgs-leaflet/GeoJSON.WFS.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/azgs-leaflet/GeoJSON.WFS.ClickResponder.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/azgs-leaflet/Popup.Centered.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/azgs-leaflet/Control.Hover.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/azgs-leaflet/Control.Panel.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/azgs-leaflet/Marker.AttributeFilter.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/azgs-leaflet/JadeContent.js"></script>
                    <script type="text/javascript" src="/leaflet-0.5.1/js/azgs-leaflet/DateFilter.js"></script>


                            var southWest = new L.LatLng(47.0, 41.3),
                                northEast = new L.LatLng(68.6, 17.5),
                                bounds = new L.LatLngBounds(southWest, northEast);
                            var map = L.map('map').setView([57.3, 29.4], 7).setMaxBounds(bounds);
                            var mapnik = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {maxZoom: 18, attribution: "Map data &copy; <a href='http://osm.org'>OpenStreetMap</a> contributors"});
```

var geojsonWfsLayer = new L.GeoJSON.WFS("/geoserver/wfs", "vae:planet_osm_polygon", {
//    pointToLayer: function(latlng) { return new L.CircleMarker(latlng); },
//    popupObj: new JadeContent("templates/example.jade"),
//    popupOptions: { maxWidth: 530, centered: false },
//    hoverFld: "name"
});

map.addLayer(geojsonWfsLayer);

not showing WFS layer(but in openlayers its ok) and what is "vae"?

**Comment by denny123** [comment]
var geojsonWfsLayer = new L.GeoJSON.WFS("/geoserver/wfs", "obldata_polygon", {
    pointToLayer: function(latlng) { return new L.CircleMarker(latlng); },
    popupObj: new JadeContent("templates/example.jade"),
    popupOptions: { maxWidth: 530, centered: false },
    hoverFld: "name",
    inputCrs: "EPSG:4326"
});
map.addLayer(geojsonWfsLayer);

Uncaught TypeError: Object [object Object] has no method 'addGeoJSON'

**Comment by denny123** [comment]
![screen2](https://f.cloud.github.com/assets/3593754/216317/514a2f82-84bd-11e2-869a-884ebbf12b39.jpg)

I changed addGeoJson on addData and working, but show with bad projection and i dunno how set right. Inputcrs: 900913, mapcrs: 3857?

**Comment by rclark** [comment]
We've moved the development of this geoserver vector layer to try and encorporate it into an existing Leaflet extension. You can check out our fork (just started last week) at https://github.com/azgs/leaflet-vector-layers

**Comment by denny123** [comment]
i know this but i dunno how install REST for PostGIS?
